name: Render and Deploy RMarkdown Website
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Create country reports"
      - "Create model reports"
    branches: [main]
    types:
      - completed
  push:
    branches: main

jobs:
  render-website:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.FORECASTHUB_TOKEN }}
          workflow: reports-country.yml
          name: country-reports
          path: reports
          repo: covid19-forecast-hub-europe

      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.FORECASTHUB_TOKEN }}
          workflow: reports-model.yml
          name: model-reports
          path: reports
          repo: covid19-forecast-hub-europe

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          install-r: false
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
          clean: true
