name: Render and Deploy RMarkdown Website
on:
  push:
    branches: main
  schedule:
    - cron: "0 16 * * 0"
    - cron: "45 11 * * 2"

jobs:
  render-reports:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'epiforecasts/covid19-forecast-hub-europe'
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev pandoc

      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("remotes", "here", "rmarkdown", "lubridate", "ggplot2", "dplyr", "DT", "knitr", "readr", "rlang", "tidyr", "forcats", "lemon", "scales", "rmdpartials", "RColorBrewer", "cowplot"))
          remotes::install_github("reichlab/covidHubUtils")
          remotes::install_github("epiforecasts/scoringutils@limit-viz")
          remotes::install_github("epiforecasts/EuroForecastHub")
        shell: Rscript {0}

      - name: Create country reports
        run: Rscript 'code/reports/compile-country-reports.r'

      - name: Create model reports
        run: Rscript 'code/reports/compile-model-reports.r'

      - uses: actions/upload-artifact@v2
        with:
          name: md-reports
          retention-days: 5
          path: html

  render-website:
    needs: render-reports
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: md-reports

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: _site
          GH_PAT: ${{ secrets.GH_PAT }}
