name: Render and Deploy RMarkdown Website
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Create country reports"
      - "Create model reports"
    branches: [main]
    types:
      - completed
  push:
    branches: main

jobs:
  render-website:
    needs: render-reports
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: country-reports
          path: reports

      - uses: actions/download-artifact@v2
        with:
          name: model-reports
          path: reports

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: _site
          GH_PAT: ${{ secrets.GH_PAT }}
