name: "Create model reports"
on:
  workflow_dispatch:
  schedule:
    - cron: "45 11 * * 2"

jobs:
  model_reports:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.FORECASTHUB_TOKEN }}
          repository: 'covid19-forecast-hub-europe/covid19-forecast-hub-europe'

      - uses: r-lib/actions/setup-r@v1
        with:
          install-r: false
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev pandoc

      - uses: r-lib/actions/setup-renv@v2

      - name: Create model reports
        run: Rscript 'code/reports/compile-model-reports.r'

      - uses: actions/upload-artifact@v2
        with:
          name: model-reports
          retention-days: 8
          path: |
            html/

      - name: Create issue about failure
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: JasonEtco/create-an-issue@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/action-issue-template.md
