name: "Create model reports"
on:
  workflow_dispatch:
  schedule:
    - cron: "45 11 * * 2"

jobs:
  model_reports:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'epiforecasts/covid19-forecast-hub-europe'
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev pandoc

      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("remotes", "here", "rmarkdown", "lubridate", "ggplot2", "dplyr", "DT", "knitr", "readr", "rlang", "tidyr", "forcats", "lemon", "scales", "rmdpartials", "RColorBrewer", "cowplot"))
          remotes::install_github("reichlab/covidHubUtils")
          remotes::install_github("epiforecasts/scoringutils@limit-viz")
          remotes::install_github("epiforecasts/EuroForecastHub")
        shell: Rscript {0}

      - name: Create model reports
        run: Rscript 'code/reports/compile-model-reports.r'

      - uses: actions/upload-artifact@v2
        with:
          name: model-reports
          retention-days: 8
          path: |
            html/

      - name: Create issue about failure
        if: failure() && github.event_name != 'workflow_dispatch'
        uses: JasonEtco/create-an-issue@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/action-issue-template.md
